apiVersion: v1
kind: Service
metadata:
  name: firefox
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: firefox
  ports:
    - name: gui
      port: 8082
      targetPort: 8082
      protocol: TCP
